#!/usr/bin/env bash
# script to install nginx on a server
apt-get update
apt-get install -y nginx

echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
  listen 80;
  listen [::]:80 default_server;
  root   /var/www/html;
  index  index.htm index.html;

  location /redirect_me {
    return 301 https://www.github.com/RichardMiruka/;
  }

  error_page 404 /404.html;
  location /404.html {
    root /etc/nginx/html;
    internal;
  }
  }" > /etc/nginx/sites-available/default

service nginx restart
